#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

#LA removed due to write perimissions
# ./installVersion.sh

wmake

# ----------------------------------------------------------------- end-of-file
